### ISSUE TITLE
images do not seem to have the correct name and platform labels

### ISSUE THREAD

**Issue by aaronlippold** [plus3it/spel#149] opened 2018-02-16 02:33 UTC
When using the kitchen-ec2 driver in govcloud, the image_search is not able to find the images for spel when searching for generic 'centos' or 'centos-7' images.

Per the readme: https://github.com/test-kitchen/kitchen-ec2 here: https://github.com/test-kitchen/kitchen-ec2#specifying-the-image it would be very useful if kitchen could return the correct platform image list for centos-6 and 7. 

I am hoping the fix is just adding the right labels to the build process in your images.

**Comment by ferricoxide** [comment] 2018-02-16 02:56
Looking solely at the project-dox (and not digging into the query-code):

> Note that the image_search method requires that the AMI image names be in a specific format. Some examples are:
>
> * Windows-2012
> * Windows-2012r2
> * Windows-2012r2sp1
> * RHEL-7.2

It reads like we would need to alter our AMI naming-scheme rather than adding tags? Can you furnish some exemplar AMI-IDs that _do_ work with the tool you're trying to leverage?

**Comment by ferricoxide** [comment] 2018-02-16 04:14
In looking at the attributes of a "vendor" AMI and one of our AMIs, the only fields it appears the tool could be trying to match on are the `Name:` or the `ImageLocation` fields. It would appear that kitchen's tokenizer may be a bit too rigid in how it identifies platforms (consistent with the above note in its dox). 

It appears that Kitchen allows you to search by `platform` name, `image_id`, or `image_search`. Perhaps you would have more success leveraging `image_search` instead of `platform` name?

**Comment by lorengordon** [comment] 2018-02-16 11:38
As we do not use test kitchen, and this appears to be either an issue for test kitchen, a usage question for test kitchen, I'm going to go ahead and close this issue. As @ferricoxide indicated, it appears it is already possible to find custom images using the `image_search` functionality:

* https://github.com/test-kitchen/kitchen-ec2/issues/147#issuecomment-230134799
* https://github.com/test-kitchen/kitchen-ec2#image_search

If I'm interpreting the doc and other examples correctly, when using `image_search`, the platform `name` is not used at all to find the image.

If in your investigation you do find something we can address in the code here, feel free to reopen with sufficient details to reproduce the problem. At a minimum, we'll need an example test kitchen project and instructions on how to install, setup, and use test kitchen in a way that demonstrates both a working image search and the non-working image search.

**Closed by lorengordon** 2018-02-16 11:38 UTC

**Comment by aaronlippold** [comment] 2018-02-16 14:49
I am happy to send some examples and will do so. I tried to use the aws cli with the --filters with no luck.

**Comment by aaronlippold** [comment] 2018-02-16 14:57
Thanks all, I think @ferricoxide may be correct. Let me put a couple things together and I will ping you back with working examples and broken ones. 

My hope is it may just need a small refactoring in the naming style - like `<platform>-<version>-spel-*`. If this small update in the pattern would produce a loosely coupled integration then I am all for it.

Many of the govcloud users are using kitchen and the tool-chain as well as the spel images and they have had to resort to using specific image id's to get their pipeline to work. This is less than ideal given that you guys have a processes for pushing updates and we want to make using those updates in a  seamless and transparent as possible. Otherwise we have to take on an unneeded upkeep process or scripting magic to account for something that could be resolved by standardization on naming conventions.

**Comment by lorengordon** [comment] 2018-02-16 15:06
Here is an example using the aws cli. This will return all the spel centos 7.4 images. I still don't really see anything that seems like any change would be needed to this project.

```
aws ec2 describe-images --filters Name=owner-id,Values=701759196663 Name=name,Values=spel-minimal-centos-7.4-hvm-*.x86_64-gp2
```

Based on that, I would expect this test-kitchen config to work:

```
platforms:
  - name: centos-7.4
    driver:
      image_search:
        owner-id: "701759196663"
        name: spel-minimal-centos-7.4-hvm-*.x86_64-gp2
```

That's for the commercial regions. For GovCloud, the owner-id is 039368651566.

**Comment by aaronlippold** [comment] 2018-02-16 15:18
Thanks @lorengordon I will test that out and see if it works. If so, the question of is there a specific need for that naming format to be `spel-minimal-centos-7.4-hvm-*.x86_64-gp2` rather than `centos-7.4-spel-minimal-hvm-*.x86_64-gp2`. I am hoping this would be the least intrusive way to achieve a stable shared solution.

This would then allow your above example in .kitchen.yml to be something like:

```
platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts
```

Pulling down the `latest` from your work without having to worry about image ids and or owner ids between commercial and govcloud.

**Comment by lorengordon** [comment] 2018-02-16 15:30
@aaronlippold I do not believe that will work. The [test kitchen docs](https://github.com/test-kitchen/kitchen-ec2#platform-name) are clear that the platform name-based search **only** works with _official_ vendor images. No spel image will ever be an official vendor image. As far as I can tell, the standard way for people to use custom images with test kitchen is the `image_search` functionality based around aws cli filters.

> If you use the platform name ubuntu, windows, rhel, debian, centos, freebsd or fedora, kitchen-ec2 will search for the latest matching official image of the given OS in your region.

If test kitchen _can't_ work with custom images with arbitrary image names, that's a bug (or feature request) for test kitchen not spel.

**Comment by aaronlippold** [comment] 2018-02-16 16:08
Thanks all, I will proceed with the 'image_search' solution and once I have better insight into govclouds standardized naming convention perhaps we can see if enhancement could improve the overall user experience. Thanks everyone for your time and input.

**Comment by cheeseplus** [comment] 2018-02-16 17:39
Friendly neighborhood kitchen maintainer here to say that `image_search` is definitely what we recommend here. The snippets above are highly specific to `kitchen-dokken` and as such aren't great starting points to reason from.

The example is spot on here for intended use.
```
platforms:
  - name: centos-7.4
    driver:
      image_search:
        owner-id: "701759196663"
        name: spel-minimal-centos-7.4-hvm-*.x86_64-gp2
```

If the naming convention is standardized enough _and_ it's consistent across regions then I can see us accepting a PR to enhance the defaults [here ](https://github.com/test-kitchen/kitchen-ec2/tree/master/lib/kitchen/driver/aws/standard_platform). We only do search automatically in the case where the platform name fits a certain subset of platforms and _no_ additional configuration is provided - essentially for the avg user who might not be aware of AMI ids or search so we can have some friendly UX. This logic _can_ be extended but this is still enough of a niche use case that given `image_search` works fine that it seems a bit of gold plating for a very small subset of users. 

Would we merge a PR for it? Probably if it was well tested and scoped. Would I write it myself? Probably not at this juncture.

**Comment by ferricoxide** [comment] 2018-02-16 17:47
@cheeseplus Thanks for chiming in! =)
